#!/usr/bin/env python3

"""
@file     pmenu
@brief    Sleek dmenu alternative written in Python and powered by curses.
@date     25/07/2023
@author   Julio Cabria
"""

import sys
import curses
from contextlib import suppress

TMP_FILE = "/tmp/pmenu"
YELLOW = "\033[1;33m"
CYAN = "\033[1;36m"
RESET = "\033[0;0m"


def display_menu(stdscr, lines):
    """
    Display a menu with the given lines and return the selected option.

    Args:
        stdscr: The curses screen.
        lines: The lines to display in the menu.

    Returns:
        The selected option or None if the user quit the menu.
    """
    current_row = 0
    curses.curs_set(0)
    curses.use_default_colors()

    while True:
        stdscr.clear()

        max_rows, _ = stdscr.getmaxyx()
        max_display_rows = min(max_rows, len(lines))

        start_row = max(0, current_row - max_rows + 1)
        end_row = start_row + max_display_rows

        # Populate the screen with the lines
        for i, line in enumerate(lines[start_row:end_row], start=start_row):
            with suppress(curses.error):
                if i == current_row:
                    stdscr.addstr(i - start_row, 0, line, curses.A_REVERSE)
                    continue
                stdscr.addstr(i - start_row, 0, line)

        stdscr.refresh()

        # Read a key from the keyboard
        key = stdscr.getch()
        if key == curses.KEY_UP:
            if current_row > 0:
                current_row -= 1
            elif start_row > 0:
                start_row -= 1
        elif key == curses.KEY_DOWN:
            if current_row < len(lines) - 1:
                current_row += 1
            elif end_row < len(lines):
                start_row += 1
        elif key == ord('q'):
            return None
        elif key == ord('\n'):
            return lines[current_row]


def pmenu(lines):
    """
    Display a menu with the given lines and return the selected option.

    Args:
        lines: The lines to display in the menu.

    Returns:
        The selected option or None if the user quit the menu.
    """
    return curses.wrapper(display_menu, lines)


if __name__ == "__main__":

    if len(sys.argv) == 2:
        text = sys.argv[1].split("\n")
    elif len(sys.argv) > 2:
        text = sys.argv[1:]
    else:
        print(f"\nUsage:\n"
              f"  {CYAN}pmenu  "
              f"{YELLOW}\"line1{CYAN}\\n"
              f"{YELLOW}line2{CYAN}\\n"
              f"{YELLOW}line3...\"{RESET}\n"
              f"         {YELLOW}\"line1\" \"line2\" \"line3\" ...{RESET}")

        print("\nBindings:\n"
              f"  {CYAN}up     {RESET}Highlight previous option.\n"
              f"  {CYAN}down   {RESET}Highlight next option.\n"
              f"  {CYAN}enter  {RESET}Select highlighted option, "
              f"will be written to {YELLOW}\"/tmp/pmenu\"{RESET}.\n"
              f"  {CYAN}q      {RESET}Quit menu and exit with code 1.\n")

        sys.exit(1)

    text = [line
            for line in text
            if line != ""]

    selected_option = pmenu(text)
    if selected_option is not None:
        with open(TMP_FILE, "w", encoding="utf-8") as f:
            f.write(selected_option)
        sys.exit(0)
    sys.exit(2)
